version: '3.8'

services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - ./backend:/app
      ports:
        - "8000:8000"
      env_file:
        - backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
          - ./frontend:/app
          - ./frontend/node_modules:/app/node_modules
    command: ["sh", "-c", "npm install && npm run dev"]

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/live/citestingx.com:/etc/letsencrypt/live/citestingx.com:ro
        - /etc/letsencrypt/archive/citestingx.com:/etc/letsencrypt/archive/citestingx.com:ro

      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - frontend
        - backend