version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app  # Mounts the current directory to /app inside the container
      - /app/node_modules  # Ensures node_modules are isolated
